apiVersion: v1
kind: Service
metadata:
  name: express-cloud-setup
spec:
  selector:
    app: express-cloud-setup
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000