apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
spec:
  selector:
    matchLabels:
      app: express-cloud-setup
  template:
    metadata:
      labels:
        app: express-cloud-setup
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
        prometheus.io/path: '/prometheus/metricsAsString'
    spec:
      containers:
      - name: express-cloud-setup
        image: express-cloud-setup
        imagePullPolicy: Never
        ports:
            - containerPort: 3000
      restartPolicy: Always